server.port: 8761spring:  application.name: discovery-server
  cloud.config.uri: http://localhost:8888
  profiles.active: dev  ## eureka server should not register with eurekaeureka:  client:    register-with-eureka: false    fetch-registry: false